import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
} from "react";

export type LanguageCode =
  | "en"
  | "jp"
  | "zh-Hant"
  | "zh-Hans"
  | "fr"
  | "es"
  | "pt"
  | "ko"
  | "de"
  | "ar";

export interface LanguageOption {
  code: LanguageCode;
  path: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", path: "/en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "jp", path: "/jp", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "zh-Hant", path: "/zh-Hant", name: "Traditional Chinese", nativeName: "繁體中文", flag: "🇭🇰" },
  { code: "zh-Hans", path: "/zh-Hans", name: "Simplified Chinese", nativeName: "简体中文", flag: "🇨🇳" },
  { code: "fr", path: "/fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "es", path: "/es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "pt", path: "/pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "ko", path: "/ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "de", path: "/de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "ar", path: "/ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    madeWith: "Made with",
    by: "by Pierre Kollo. Powered by advanced AI.",
    contact: "Contact",
    language: "Language",
    selectLanguage: "Select Language",
    home: "Home",
    read: "Read",
    create: "Create",
    convert: "Convert",
    heroTitle: "Your Ultimate All-in-One E-book & Comic Suite",
    heroSubtitle: "Read, convert, and create dynamic comics, text novels, or media-rich PDFs. Optimized for mobile, desktop, and E-ink devices.",
    readCardTitle: "Guided Reading: Comics & Text Optimized",
    readCardDesc: "Optimized for mobile and E-ink screens. Focuses on comic panels for manga, or reflows dense book layouts so you can stop pinching and squinting.",
    accessBookshelf: "Access Bookshelf →",
    createCardTitle: "Online Comic Maker & Novel Writer",
    createCardDesc: "An intuitive rich-text workspace. Author traditional e-book novels, compile script outlines, or design multi-panel comic strips and overlay balloons.",
    launchCanvasCreator: "Launch Canvas Creator →",
    convertCardTitle: "Universal E-book Converter",
    convertCardDesc: "Effortlessly batch-convert CBZ, CBR, PDF, and EPUB files. Compresses graphic novels and formats textbook layouts into Kindle-ready EPUBs.",
    uploadAndConvertNow: "Upload & Convert Now →",
    keyFeaturesTitle: "Key Suite Capabilities & Online Tools",
    featAiTranslateTitle: "AI Translation Tool",
    featAiTranslateDesc: "Translate Japanese raw manga and webtoons using cutting-edge AI OCR. Automatically detect speech bubbles and clean manga text online.",
    featMultiAiTitle: "Choose Multi-AI Provider",
    featMultiAiDesc: "Choose from free models, Gemini, OpenAI, Claude, or local LLMs for flexible text translation, OCR processing, and generation.",
    featSplitterTitle: "Comic Panel Splitter",
    featSplitterDesc: "Intelligently crop and split comic strips into guided view segments, delivering an optimized mobile e-reader experience for any device.",
    featCbzEpubTitle: "CBZ to EPUB Converter",
    featCbzEpubDesc: "Instantly convert zipped comic archives (CBZ/ZIP) into standard EPUB format eBooks, ensuring high compatibility with digital readers.",
    featAiAgentTitle: "Create with AI Agent",
    featAiAgentDesc: "Collaborate with an AI agent to generate storylines, format dialogue balloons, brainstorm comic panel layouts, and structure e-books.",
    featLocalProcTitle: "Private Local Processing",
    featLocalProcDesc: "Self-hosted configurations available with containerized environments, ensuring your comic projects remain private and securely offline.",
    featFormatSupportTitle: "Universal Format Support",
    featFormatSupportDesc: "Seamlessly open, view, and convert CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP, and HTML files with clean responsive rendering.",
    featPenSupportTitle: "Pen Support",
    featPenSupportDesc: "This app supports Wacom or Apple Pencil features like tilt and pressure sensitivity. Draw like a professional artist.",
    buyCoffee: "Buy me a coffee",
    supportEbookcc: "Support ebookcc! 🎉",
    supportCoffeeDesc: "Thank you for using ebookcc! If this tool made your reading and editing experience better, please consider supporting the creator with a coffee. Every support keeps the servers ticking!",
    supportKoFi: "Support on Ko-fi",
    maybeLater: "Maybe later",
    appSettings: "App Settings",
    toggleTheme: "Toggle theme",
    dragDropEbookFiles: "Drag & Drop Comic/eBook Files Here",
    supportedFormats: "Supported",
    browseLocalFiles: "or click inside this workspace block to browse local files",
    quickAiGenTitle: "Quick AI Generation",
    quickAiGenDesc: "Simply sign in to start generating AI comics, stories, and translations instantly. No need to enter or manage API keys manually!",
    aiProvider: "AI Provider",
    convertFeatureHint: "OCR scanning, panel splitting, translation & eBook packager will guide you step by step.",
    recentConversions: "Recent Conversions",
    confirmClearConversions: "Are you sure you want to clear all conversion history?",
    conversionHistoryCleared: "Conversion history cleared.",
    clearAllPages: "Clear All Pages",
    export: "Export",
    sendToKindle: "Send to Kindle",
    hideSidebar: "Hide Sidebar",
    showSidebar: "Show Sidebar",
    insertImage: "Insert Image",
    addText: "Add Text",
    select: "Select",
    done: "Done",
    addPage: "Add Page",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    processingBatch: "Processing Batch...",
    aiAnalyzingComic: "AI is analyzing and translating your comic",
    stopBatch: "Stop Batch",
    exportComplete: "Export Complete! 🎉",
    supportCoffeeModalDesc: "Thank you for using EbookCC! If this tool saved you time and made your comic-reading journey better, please consider supporting the creator with a coffee.",
    recentlyRead: "Recently Read",
    confirmClearHistory: "Are you sure you want to clear your reading history?",
    historyCleared: "History cleared.",
    clearHistory: "Clear History",
    writeAStory: "Write a story",
    createComicCardTitle: "Create Comic",
    aiAgentGreeting: "👋 Hi! I can help brainstorm ideas, write scripts, or draw something. What would you like to create?",
    freeComicCreatorTitle: "Free Comic Book & Manga Creator",
    freeComicCreatorDesc: "Draw panel pages, add classic and action speech bubbles, and render storyboard shapes.",
    richTextEditorTitle: "Rich Text Script & Document Editor",
    richTextEditorDesc: "Write stories, novels, scripts, or screenplays with headings and inline illustrations.",
    publishedWorks: "Published Works",
    noPublishedWorks: "No published works found.",
    noPublishedWorksDesc: "Create a comic or story and click \"Publish\" in the editor header to feature it here and on the main bookshelf.",
    previousUnfinishedComics: "Previous Unfinished Comics",
    previousUnfinishedStories: "Previous Unfinished Stories",
    signInToSync: "Sign In to Sync",
    edit: "Edit",
    deleteWork: "Delete Work",
    readOnly: "Read-Only",
    bubblesCount: "Bubbles",
    deleteProject: "Delete project",
    signInLogin: "Sign In / Login",
    signOut: "Sign Out",
    cancel: "Cancel",
    saveAndContinue: "Save and Continue",
    signInToEbookCC: "Sign In to eBookCC",
    createWorkspaceAccount: "Create Workspace Account",
    accessCloudBooks: "Access your cloud books and sync your publishing preferences.",
    gainSecureAccess: "Gain secure access to synchronize novels, comic layouts, and visual templates.",
    continueWithGoogle: "Continue with Google",
    orEmailLogin: "Or email login",
    displayName: "Display Name",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot password?",
    signInSecurely: "Sign In Securely",
    verifyCodeRegister: "Verify Code & Register Account",
    alreadyHaveAccount: "Already have an account? Sign In",
    needWorkspaceSignUp: "Need a professional workspace? Sign Up Free",
    authorizationCode: "Authorization Code",
    sendCode: "Send Code",
    resendCode: "Resend Code",
    sendingCode: "Sending...",
    setNewPassword: "Set New Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    updatePasswordSignIn: "Update Password & Sign In",
    enterAuthCode: "Enter Authorization Code",
    verifyCodeComplete: "Verify Code & Complete Sign Up",
    backToSignIn: "Back to Sign In",
    requestNewCode: "Code expired or having issues? Request a new code",
    uploadImageTooltip: "Upload Image",
    takePhotoTooltip: "Take Photo",
    readCanvasTooltip: "Read Canvas/Sketch",
    voiceInputTooltip: "Voice Input",
    insertIntoProject: "Insert into Project",
    dragToMoveBubble: "Drag to move bubble",
    allProcessAll: "All (process all)",
    cropPageBorders: "Crop Page Borders",
    cropPageBordersDesc: "Detect and remove page margins",
    splitPanels: "Split Panels",
    splitPanelsDesc: "Detect and individualize panels",
    extractTextOcr: "Extract Text (OCR)",
    extractTextOcrDesc: "Extract text via Gemini Flash",
    translateText: "Translate Text",
    processCurrentPage: "Process Current Page",
    batchProcessAll: "Batch Process All",
    batchProcessSelected: "Batch Process Selected ({count})",
    pageTexts: "Page {page} Texts",
    detectingLayout: "Detecting layout...",
    freeAiDefault: "Free AI (Default)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Gemini AI Cloud Engine",
    geminiDesc: "We use gemini-flash-latest by default. You need a personal API key to process images or run translations.",
    getGeminiKeyFree: "🔥 Get your free Gemini API Key here (15 requests per minute free)",
    geminiApiKeyLabel: "Gemini API Key",
    geminiKeyStorageNote: "Your key is stored only in your browser's local storage.",
    modelNameLabel: "Model Name",
    puterDesc: "Puter.js provides access to Mistral/Pixtral models for OCR. A login prompt will appear if you are not already signed in to Puter.",
    localLlmDesc: "Connect to Ollama, LM Studio, or any OpenAI-compatible custom endpoint. The model must support JSON mode and vision capabilities.",
    otherProviderDesc: "Provide the Base URL, API Key, and Model name for your provider. We expect an OpenAI-compatible endpoint.",
    apiBaseUrl: "API Base URL",
    customModel: "Custom Model...",
    typeCustomModelName: "Type custom model name...",
    askAiAgent: "Ask AI Agent...",
    slideReorganizeComics: "Reorganize Comics",
    slideCreateComic: "Create Comic",
    slideAddTextInsertImages: "Add text, Insert images",
  },
  jp: {
    madeWith: "制作",
    by: "Pierre Kollo による制作。高度なAIを搭載。",
    contact: "お問い合わせ",
    language: "言語",
    selectLanguage: "言語を選択",
    home: "ホーム",
    read: "読む",
    create: "作成",
    convert: "変換",
    heroTitle: "オールインワンの電子書籍＆コミック総合スイート",
    heroSubtitle: "動的なコミック、小説、メディア豊富なPDFの閲覧・変換・作成。モバイル、デスクトップ、E-ink端末に最適化。",
    readCardTitle: "ガイド付き閲覧：コミック＆テキスト最適化",
    readCardDesc: "モバイルやE-ink画面に最適化。マンガのコマ表示や密度の高い書籍レイアウトの再構成に対応。",
    accessBookshelf: "本棚を開く →",
    createCardTitle: "オンラインコミックメーカー＆小説執筆",
    createCardDesc: "直感的なリッチテキスト環境。電子書籍の執筆、プロット作成、コマ割りや吹き出しのデザインが可能。",
    launchCanvasCreator: "キャンバスクリエイターを起動 →",
    convertCardTitle: "万能電子書籍コンバーター",
    convertCardDesc: "CBZ、CBR、PDF、EPUBファイルを一括変換。グラフィックノベルの圧縮やKindle用EPUB出力に対応。",
    uploadAndConvertNow: "今すぐアップロードして変換 →",
    keyFeaturesTitle: "主な機能＆オンラインツール",
    featAiTranslateTitle: "AI翻訳ツール",
    featAiTranslateDesc: "先進のAI OCRで日本語の原作マンガやウェブトゥーンを翻訳。吹き出しの自動検知とテキストクリーンアップに対応。",
    featMultiAiTitle: "マルチAIプロバイダー選択",
    featMultiAiDesc: "無料モデル、Gemini、OpenAI、Claude、ローカルLLMから選択してテキスト翻訳やOCRを柔軟に実行。",
    featSplitterTitle: "コミックパネルスプリッター",
    featSplitterDesc: "コミックのコマをスマートに切り出し・分割し、あらゆるデバイスに最適化された閲覧体験を提供。",
    featCbzEpubTitle: "CBZ から EPUB 変換",
    featCbzEpubDesc: "圧縮されたコミックアーカイブ（CBZ/ZIP）を標準EPUBフォーマットに瞬時に変換。",
    featAiAgentTitle: "AIエージェントと創作",
    featAiAgentDesc: "AIエージェントと連携してストーリー構築、台詞吹き出しの整形、コマ割りのアイディア出しをサポート。",
    featLocalProcTitle: "プライベートローカル処理",
    featLocalProcDesc: "セルフホスト環境やコンテナ環境に対応し、作品プロジェクトを安全にオフライン保護。",
    featFormatSupportTitle: "万能フォーマット対応",
    featFormatSupportDesc: "CBZ、CBR、EPUB、PDF、DOCX、TXT、WEBP、HTMLファイルをスムーズに開いて変換・表示。",
    featPenSupportTitle: "ペン入力対応",
    featPenSupportDesc: "WacomやApple Pencilの傾き・筆圧感知に対応。プロのイラストレーターのように描画可能。",
    buyCoffee: "コーヒーをおごる",
    supportEbookcc: "ebookcc を応援する！ 🎉",
    supportCoffeeDesc: "ebookccをご利用いただきありがとうございます！読書や編集体験の向上に役立ちましたら、開発者へのコーヒーの差し入れをご検討いただけますと幸いです。",
    supportKoFi: "Ko-fi で応援する",
    maybeLater: "あとで",
    appSettings: "アプリ設定",
    toggleTheme: "テーマ切替",
    dragDropEbookFiles: "コミック/電子書籍ファイルをここにドラッグ＆ドロップ",
    supportedFormats: "対応フォーマット",
    browseLocalFiles: "またはここをクリックしてローカルファイルを参照",
    quickAiGenTitle: "クイックAI生成",
    quickAiGenDesc: "サインインするだけで、AIコミック、ストーリー、翻訳を今すぐ生成開始できます。APIキーの手動入力や管理は不要です！",
    aiProvider: "AIプロバイダー",
    convertFeatureHint: "OCRスキャン、コマ割り、翻訳、電子書籍パッケージ作成がステップバイステップでガイドします。",
    recentConversions: "最近の変換履歴",
    confirmClearConversions: "変換履歴をすべて消去してもよろしいですか？",
    conversionHistoryCleared: "変換履歴を消去しました。",
    clearAllPages: "全ページ消去",
    export: "エクスポート",
    sendToKindle: "Kindleへ送信",
    hideSidebar: "サイドバーを隠す",
    showSidebar: "サイドバーを表示",
    insertImage: "画像を挿入",
    addText: "テキスト追加",
    select: "選択",
    done: "完了",
    addPage: "ページ追加",
    selectAll: "すべて選択",
    deselectAll: "選択解除",
    processingBatch: "バッチ処理中...",
    aiAnalyzingComic: "AIがコミックを解析・翻訳中",
    stopBatch: "バッチ停止",
    exportComplete: "エクスポート完了！ 🎉",
    supportCoffeeModalDesc: "EbookCCをご利用いただきありがとうございます！読書や編集に役立ちましたら、開発者へのコーヒーの差し入れをご検討ください。",
    recentlyRead: "最近読んだ本",
    confirmClearHistory: "読書履歴を消去してもよろしいですか？",
    historyCleared: "履歴を消去しました。",
    clearHistory: "履歴を消去",
    writeAStory: "物語を書く",
    createComicCardTitle: "コミック作成",
    aiAgentGreeting: "👋 こんにちは！アイディア出し、脚本執筆、描画をお手伝いします。何を作成しますか？",
    freeComicCreatorTitle: "無料のコミック・マンガ作成機能",
    freeComicCreatorDesc: "コマ割りの描画、クラシック・アクション吹き出しの配置、絵コンテのドラッグ＆ドロップに対応。",
    richTextEditorTitle: "リッチテキスト脚本・ドキュメントエディター",
    richTextEditorDesc: "見出しや挿絵付きの小説、スクリプト、シナリオを執筆・編集できます。",
    publishedWorks: "公開済みの作品",
    noPublishedWorks: "公開済みの作品はありません。",
    noPublishedWorksDesc: "コミックや小説を作成し、ヘッダーの「公開」をクリックするとここに掲載されます。",
    previousUnfinishedComics: "作成途中のコミック",
    previousUnfinishedStories: "作成途中の小説・ストーリー",
    signInToSync: "サインインして同期",
    edit: "編集",
    deleteWork: "作品を削除",
    readOnly: "閲覧専用",
    bubblesCount: "個の吹き出し",
    deleteProject: "プロジェクトを削除",
    signInLogin: "サインイン / ログイン",
    signOut: "サインアウト",
    cancel: "キャンセル",
    saveAndContinue: "保存して続行",
    signInToEbookCC: "eBookCC にサインイン",
    createWorkspaceAccount: "ワークスペースアカウントを作成",
    accessCloudBooks: "クラウド上の本にアクセスし、出版設定を同期します。",
    gainSecureAccess: "小説、コミックのレイアウト、視覚テンプレートを同期します。",
    continueWithGoogle: "Google で続行",
    orEmailLogin: "またはメールアドレスでログイン",
    displayName: "表示名",
    emailAddress: "メールアドレス",
    password: "パスワード",
    forgotPassword: "パスワードをお忘れですか？",
    signInSecurely: "安全にサインイン",
    verifyCodeRegister: "認証コードを確認してアカウント登録",
    alreadyHaveAccount: "すでにアカウントをお持ちですか？ サインイン",
    needWorkspaceSignUp: "アカウントをお持ちでないですか？ 無料登録",
    authorizationCode: "認証コード",
    sendCode: "コードを送信",
    resendCode: "コードを再送",
    sendingCode: "送信中...",
    setNewPassword: "新しいパスワードを設定",
    newPassword: "新しいパスワード",
    confirmNewPassword: "新しいパスワードの確認",
    updatePasswordSignIn: "パスワードを更新してサインイン",
    enterAuthCode: "認証コードを入力",
    verifyCodeComplete: "認証コードを確認して登録完了",
    backToSignIn: "サインインに戻る",
    requestNewCode: "コードの有効期限が切れましたか？ 新しいコードをリクエスト",
    uploadImageTooltip: "画像をアップロード",
    takePhotoTooltip: "写真を撮影",
    readCanvasTooltip: "キャンバス/スケッチを読み取る",
    voiceInputTooltip: "音声入力",
    insertIntoProject: "プロジェクトに挿入",
    dragToMoveBubble: "ドラッグして吹き出しを移動",
    allProcessAll: "すべて (一括処理)",
    cropPageBorders: "ページの余白をトリミング",
    cropPageBordersDesc: "余白を自動検出して除去",
    splitPanels: "コマ割り (パネル分割)",
    splitPanelsDesc: "コマを個別検出して分割",
    extractTextOcr: "テキスト抽出 (OCR)",
    extractTextOcrDesc: "Gemini Flashでテキスト抽出",
    translateText: "テキスト翻訳",
    processCurrentPage: "現在のページを処理",
    batchProcessAll: "全ページを一括処理",
    batchProcessSelected: "選択した {count} ページを一括処理",
    pageTexts: "ページ {page} のテキスト",
    detectingLayout: "レイアウトを検出中...",
    freeAiDefault: "無料AI (デフォルト)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Gemini AI クラウドエンジン",
    geminiDesc: "デフォルトで gemini-flash-latest を使用します。画像の処理や翻訳には個人のAPIキーが必要です。",
    getGeminiKeyFree: "🔥 無料のGemini APIキーを取得 (1分間15リクエストまで無料)",
    geminiApiKeyLabel: "Gemini API キー",
    geminiKeyStorageNote: "APIキーはお使いのブラウザのローカルストレージにのみ保存されます。",
    modelNameLabel: "モデル名",
    puterDesc: "Puter.jsはMistral/PixtralモデルによるOCR機能を提供します。未ログインの場合はログイン画面が表示されます。",
    localLlmDesc: "Ollama、LM Studio、またはOpenAI互換のカスタムエンドポイントに接続します。モデルはJSONモードとビジョンに対応している必要があります。",
    otherProviderDesc: "プロバイダーのベースURL、APIキー、モデル名を入力してください。OpenAI互換エンドポイントが必要です。",
    apiBaseUrl: "API ベース URL",
    customModel: "カスタムモデル...",
    typeCustomModelName: "カスタムモデル名を入力...",
    askAiAgent: "AIエージェントに質問...",
    slideReorganizeComics: "コミックを再構成",
    slideCreateComic: "コミックを作成",
    slideAddTextInsertImages: "テキスト追加＆画像挿入",
  },
  "zh-Hant": {
    madeWith: "精心製作",
    by: "由 Pierre Kollo 用心製作。由先進 AI 驅動。",
    contact: "聯絡我們",
    language: "語言",
    selectLanguage: "選擇語言",
    home: "首頁",
    read: "閱讀",
    create: "創作",
    convert: "轉換",
    heroTitle: "您的全方位電子書與漫畫創作閱讀工具",
    heroSubtitle: "閱讀、轉換與創作動態漫畫、文字小說或多媒體 PDF。針對手機、電腦與電子紙（E-ink）設備最佳化。",
    readCardTitle: "引導式閱讀：漫畫與文本最佳化",
    readCardDesc: "專為手機與 E-ink 螢幕設計，支援漫畫分鏡聚焦與書籍重排，告別拉大放小的閱讀不便。",
    accessBookshelf: "開啟我的書架 →",
    createCardTitle: "線上漫畫製作與小說撰寫",
    createCardDesc: "直覺的富文本創作空間，輕鬆撰寫電子小說、編排劇本大綱，或設計多格漫畫與對話框。",
    launchCanvasCreator: "啟動畫布創作器 →",
    convertCardTitle: "全能電子書轉換器",
    convertCardDesc: "輕鬆批次轉換 CBZ、CBR、PDF 和 EPUB 檔案。支援圖像壓縮與適合 Kindle 的 EPUB 匯出。",
    uploadAndConvertNow: "立即上傳並轉換 →",
    keyFeaturesTitle: "核心功能與線上工具",
    featAiTranslateTitle: "AI 漫畫翻譯工具",
    featAiTranslateDesc: "使用先進的 AI OCR 翻譯日文原稿漫畫與條漫，自動識別對話框並進行文字抹除與翻譯。",
    featMultiAiTitle: "多 AI 模型靈活選擇",
    featMultiAiDesc: "支援免費模型、Gemini、OpenAI、Claude 及本地 LLM，靈活滿足文字翻譯與 OCR 需求。",
    featSplitterTitle: "漫畫分鏡切分器",
    featSplitterDesc: "智慧裁切與切分漫畫頁面，在行動裝置上提供流暢的逐格引導閱讀體驗。",
    featCbzEpubTitle: "CBZ 轉 EPUB 轉換器",
    featCbzEpubDesc: "將 CBZ/ZIP 漫畫壓縮檔快速轉換為標準 EPUB 電子書，高度相容各式閱讀器。",
    featAiAgentTitle: "AI 助手協同創作",
    featAiAgentDesc: "與 AI 助手共同構思故事情節、排版對話框、設計漫畫分鏡與電子書結構。",
    featLocalProcTitle: "私密本地化處理",
    featLocalProcDesc: "支援容器化與自建環境，確保您的漫畫專案與資料保持隱私且安全離線。",
    featFormatSupportTitle: "萬能格式支援",
    featFormatSupportDesc: "流暢開啟與轉換 CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP, HTML 等多種格式。",
    featPenSupportTitle: "手寫筆繪圖支援",
    featPenSupportDesc: "支援 Wacom 與 Apple Pencil 的傾斜與壓感功能，像專業畫家般自由創作。",
    buyCoffee: "請我喝杯咖啡",
    supportEbookcc: "支持 ebookcc！ 🎉",
    supportCoffeeDesc: "感謝您使用 ebookcc！如果這個工具提升了您的閱讀與創作體驗，歡迎請創作者喝杯咖啡，支持伺服器持續運作！",
    supportKoFi: "在 Ko-fi 上支持",
    maybeLater: "稍後再說",
    appSettings: "應用程式設定",
    toggleTheme: "切換主題",
    dragDropEbookFiles: "拖放漫畫/電子書檔案至此",
    supportedFormats: "支援格式",
    browseLocalFiles: "或點擊此區域瀏覽本地檔案",
    quickAiGenTitle: "快速 AI 生成",
    quickAiGenDesc: "只需登入即可立即開始生成 AI 漫畫、故事與翻譯。無需手動輸入或管理 API 金鑰！",
    aiProvider: "AI 模型提供商",
    convertFeatureHint: "OCR 掃描、分鏡切分、翻譯與電子書打包將引導您一步步完成。",
    recentConversions: "最近的轉換記錄",
    confirmClearConversions: "確定要清除所有轉換記錄嗎？",
    conversionHistoryCleared: "轉換記錄已清除。",
    clearAllPages: "清除所有頁面",
    export: "匯出",
    sendToKindle: "傳送到 Kindle",
    hideSidebar: "隱藏側邊欄",
    showSidebar: "顯示側邊欄",
    insertImage: "插入圖片",
    addText: "新增文字",
    select: "選擇",
    done: "完成",
    addPage: "新增頁面",
    selectAll: "全選",
    deselectAll: "取消全選",
    processingBatch: "正在批次處理...",
    aiAnalyzingComic: "AI 正在分析與翻譯您的漫畫",
    stopBatch: "停止批次處理",
    exportComplete: "匯出完成！ 🎉",
    supportCoffeeModalDesc: "感謝使用 EbookCC！如果這個工具節省了您的時間並提升了閱讀體驗，歡迎請創作者喝杯咖啡。",
    recentlyRead: "最近閱讀",
    confirmClearHistory: "確定要清除閱讀歷史記錄嗎？",
    historyCleared: "歷史記錄已清除。",
    clearHistory: "清除歷史記錄",
    writeAStory: "撰寫故事",
    createComicCardTitle: "創作漫畫",
    aiAgentGreeting: "👋 您好！我可以協助構思創意、撰寫劇本或繪製內容。今天想創作什麼呢？",
    freeComicCreatorTitle: "免費漫畫與條漫製作工具",
    freeComicCreatorDesc: "繪製分鏡頁面、新增經典與打斗對話框、即時排版故事板。",
    richTextEditorTitle: "富文本劇本與文檔編輯器",
    richTextEditorDesc: "撰寫小說、劇本、分鏡大綱，並支援標題排版與文中插圖。",
    publishedWorks: "已發布的作品",
    noPublishedWorks: "暫無已發布的作品。",
    noPublishedWorksDesc: "創作漫畫或小說後，在編輯器標頭點擊「發布」即可展示於此與主書架。",
    previousUnfinishedComics: "先前未完成的漫畫草稿",
    previousUnfinishedStories: "先前未完成的故事草稿",
    signInToSync: "登入以同步",
    edit: "編輯",
    deleteWork: "刪除作品",
    readOnly: "唯讀",
    bubblesCount: "個對話框",
    deleteProject: "刪除專案",
    signInLogin: "登入 / 註冊",
    signOut: "登出",
    cancel: "取消",
    saveAndContinue: "儲存並繼續",
    signInToEbookCC: "登入至 eBookCC",
    createWorkspaceAccount: "建立工作區帳號",
    accessCloudBooks: "存取您的雲端書籍並同步發布偏好設定。",
    gainSecureAccess: "安全同步小說、漫畫排版與視覺範本。",
    continueWithGoogle: "使用 Google 帳號繼續",
    orEmailLogin: "或使用電子郵件登入",
    displayName: "顯示名稱",
    emailAddress: "電子郵件地址",
    password: "密碼",
    forgotPassword: "忘記密碼？",
    signInSecurely: "安全登入",
    verifyCodeRegister: "驗證驗證碼並註冊帳號",
    alreadyHaveAccount: "已有帳號？ 登入",
    needWorkspaceSignUp: "還沒有帳號？ 免費註冊",
    authorizationCode: "授權驗證碼",
    sendCode: "傳送驗證碼",
    resendCode: "重新傳送驗證碼",
    sendingCode: "傳送中...",
    setNewPassword: "設定新密碼",
    newPassword: "新密碼",
    confirmNewPassword: "確認新密碼",
    updatePasswordSignIn: "更新密碼並登入",
    enterAuthCode: "輸入授權驗證碼",
    verifyCodeComplete: "驗證驗證碼並完成註冊",
    backToSignIn: "返回登入頁面",
    requestNewCode: "驗證碼已過期？ 重新請求驗證碼",
    uploadImageTooltip: "上傳圖片",
    takePhotoTooltip: "拍攝照片",
    readCanvasTooltip: "讀取畫布/草圖",
    voiceInputTooltip: "語音輸入",
    insertIntoProject: "插入至專案",
    dragToMoveBubble: "拖曳以移動對話框",
    allProcessAll: "全部 (一括處理)",
    cropPageBorders: "裁切頁面邊框",
    cropPageBordersDesc: "檢測並移除頁面邊距",
    splitPanels: "分割分鏡",
    splitPanelsDesc: "檢測並拆分單個分鏡",
    extractTextOcr: "文字識別 (OCR)",
    extractTextOcrDesc: "透過 Gemini Flash 提取文字",
    translateText: "翻譯文字",
    processCurrentPage: "處理當前頁面",
    batchProcessAll: "批處理全部頁面",
    batchProcessSelected: "批處理選中的 {count} 頁",
    pageTexts: "第 {page} 頁文字",
    detectingLayout: "正在檢測版面...",
    freeAiDefault: "免費 AI (預設)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Gemini AI 雲端引擎",
    geminiDesc: "預設使用 gemini-flash-latest。處理圖片或執行翻譯需要個人 API 金鑰。",
    getGeminiKeyFree: "🔥 免費獲取 Gemini API 金鑰 (每分鐘 15 次免費)",
    geminiApiKeyLabel: "Gemini API 金鑰",
    geminiKeyStorageNote: "您的金鑰僅儲存在瀏覽器的本機儲存空間中。",
    modelNameLabel: "模型名稱",
    puterDesc: "Puter.js 提供 Mistral/Pixtral 模型進行 OCR。若尚未登入 Puter 將跳出登入提示。",
    localLlmDesc: "連接至 Ollama、LM Studio 或任何相容 OpenAI 的自訂 API。模型需支援 JSON 模式與視覺功能。",
    otherProviderDesc: "請提供 API 基本網址、金鑰與模型名稱。系統需要相容 OpenAI 的接口。",
    apiBaseUrl: "API 基本網址",
    customModel: "自訂模型...",
    typeCustomModelName: "輸入自訂模型名稱...",
    askAiAgent: "詢問 AI 助手...",
    slideReorganizeComics: "重組漫畫頁面",
    slideCreateComic: "創作漫畫",
    slideAddTextInsertImages: "新增文字與插入圖片",
  },
  "zh-Hans": {
    madeWith: "精心制作",
    by: "由 Pierre Kollo 用心制作。由先进 AI 驱动。",
    contact: "联系我们",
    language: "语言",
    selectLanguage: "选择语言",
    home: "首页",
    read: "阅读",
    create: "创作",
    convert: "转换",
    heroTitle: "您的全方位电子书与漫画创作阅读工具",
    heroSubtitle: "阅读、转换与创作动态漫画、文字小说或多媒体 PDF。针对手机、电脑与电子纸（E-ink）设备优化。",
    readCardTitle: "引导式阅读：漫画与文本优化",
    readCardDesc: "专为手机与 E-ink 屏幕设计，支持漫画分镜聚焦与书籍重排，告别放大放小的阅读不便。",
    accessBookshelf: "打开我的书架 →",
    createCardTitle: "在线漫画制作与小说撰写",
    createCardDesc: "直观的富文本创作空间，轻松撰写电子小说、编排剧本大纲，或设计多格漫画与对话框。",
    launchCanvasCreator: "启动画布创作器 →",
    convertCardTitle: "全能电子书转换器",
    convertCardDesc: "轻松批量转换 CBZ、CBR、PDF 和 EPUB 文件。支持图像压缩与适合 Kindle 的 EPUB 导出。",
    uploadAndConvertNow: "立即上传并转换 →",
    keyFeaturesTitle: "核心功能与在线工具",
    featAiTranslateTitle: "AI 漫画翻译工具",
    featAiTranslateDesc: "使用先进的 AI OCR 翻译日文原稿漫画与条漫，自动识别对话框并进行文字修抹与翻译。",
    featMultiAiTitle: "多 AI 模型灵活选择",
    featMultiAiDesc: "支持免费模型、Gemini、OpenAI、Claude 及本地 LLM，灵活满足文本翻译与 OCR 需求。",
    featSplitterTitle: "漫画分镜切分器",
    featSplitterDesc: "智能裁剪与切分漫画页面，在移动设备上提供流畅的逐格引导阅读体验。",
    featCbzEpubTitle: "CBZ 转 EPUB 转换器",
    featCbzEpubDesc: "将 CBZ/ZIP 漫画压缩包快速转换为标准 EPUB 电子书，高度兼容各式阅读器。",
    featAiAgentTitle: "AI 助手协同创作",
    featAiAgentDesc: "与 AI 助手共同构思故事情节、排版对话框、设计漫画分镜与电子书结构。",
    featLocalProcTitle: "私密本地化处理",
    featLocalProcDesc: "支持容器化与自建环境，确保您的漫画项目与数据保持隐私且安全离线。",
    featFormatSupportTitle: "万能格式支持",
    featFormatSupportDesc: "流畅打开与转换 CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP, HTML 等多种格式。",
    featPenSupportTitle: "手写笔绘图支持",
    featPenSupportDesc: "支持 Wacom 与 Apple Pencil 的倾斜与压感功能，像专业画家般自由创作。",
    buyCoffee: "请我喝杯咖啡",
    supportEbookcc: "支持 ebookcc！ 🎉",
    supportCoffeeDesc: "感谢您使用 ebookcc！如果这个工具提升了您的阅读与创作体验，欢迎请创作者喝杯咖啡，支持服务器持续运行！",
    supportKoFi: "在 Ko-fi 上支持",
    maybeLater: "稍后再说",
    appSettings: "应用设置",
    toggleTheme: "切换主题",
    dragDropEbookFiles: "拖放漫画/电子书文件至此",
    supportedFormats: "支持格式",
    browseLocalFiles: "或点击此区域浏览本地文件",
    quickAiGenTitle: "快速 AI 生成",
    quickAiGenDesc: "只需登录即可立即开始生成 AI 漫画、故事与翻译。无需手动输入或管理 API 密钥！",
    aiProvider: "AI 模型提供商",
    convertFeatureHint: "OCR 扫描、分镜切分、翻译与电子书打包将引导您一步步完成。",
    recentConversions: "最近的转换记录",
    confirmClearConversions: "确定要清除所有转换记录吗？",
    conversionHistoryCleared: "转换记录已清除。",
    clearAllPages: "清除所有页面",
    export: "导出",
    sendToKindle: "发送到 Kindle",
    hideSidebar: "隐藏侧边栏",
    showSidebar: "显示侧边栏",
    insertImage: "插入图片",
    addText: "添加文本",
    select: "选择",
    done: "完成",
    addPage: "添加页面",
    selectAll: "全选",
    deselectAll: "取消全选",
    processingBatch: "正在批量处理...",
    aiAnalyzingComic: "AI 正在分析与翻译您的漫画",
    stopBatch: "停止批量处理",
    exportComplete: "导出完成！ 🎉",
    supportCoffeeModalDesc: "感谢使用 EbookCC！如果这个工具节省了您的时间并提升了阅读体验，欢迎请创作者喝杯咖啡。",
    recentlyRead: "最近阅读",
    confirmClearHistory: "确定要清除阅读历史记录吗？",
    historyCleared: "历史记录已清除。",
    clearHistory: "清除历史记录",
    writeAStory: "撰写故事",
    createComicCardTitle: "创作漫画",
    aiAgentGreeting: "👋 您好！我可以协助构思创意、撰写剧本或绘制内容。今天想创作什么呢？",
    freeComicCreatorTitle: "免费漫画与条漫制作工具",
    freeComicCreatorDesc: "绘制分镜页面、添加经典与打斗对话框、实时排版故事板。",
    richTextEditorTitle: "富文本剧本与文档编辑器",
    richTextEditorDesc: "撰写小说、剧本、分镜大纲，并支持标题排版与文中插图。",
    publishedWorks: "已发布的作品",
    noPublishedWorks: "暂无已发布的作品。",
    noPublishedWorksDesc: "创作漫画或小说后，在编辑器标头点击“发布”即可展示于此与主书架。",
    previousUnfinishedComics: "先前未完成的漫画草稿",
    previousUnfinishedStories: "先前未完成的故事草稿",
    signInToSync: "登录以同步",
    edit: "编辑",
    deleteWork: "删除作品",
    readOnly: "只读",
    bubblesCount: "个对话框",
    deleteProject: "删除项目",
    signInLogin: "登录 / 注册",
    signOut: "退出登录",
    cancel: "取消",
    saveAndContinue: "保存并继续",
    signInToEbookCC: "登录至 eBookCC",
    createWorkspaceAccount: "创建工作区账号",
    accessCloudBooks: "访问您的云端书籍并同步发布偏好设置。",
    gainSecureAccess: "安全同步小说、漫画排版与视觉模板。",
    continueWithGoogle: "使用 Google 账号继续",
    orEmailLogin: "或使用电子邮件登录",
    displayName: "显示名称",
    emailAddress: "电子邮件地址",
    password: "密码",
    forgotPassword: "忘记密码？",
    signInSecurely: "安全登录",
    verifyCodeRegister: "验证验证码并注册账号",
    alreadyHaveAccount: "已有账号？ 登录",
    needWorkspaceSignUp: "还没有账号？ 免费注册",
    authorizationCode: "授权验证码",
    sendCode: "发送验证码",
    resendCode: "重新发送验证码",
    sendingCode: "发送中...",
    setNewPassword: "设置新密码",
    newPassword: "新密码",
    confirmNewPassword: "确认新密码",
    updatePasswordSignIn: "更新密码并登录",
    enterAuthCode: "输入授权验证码",
    verifyCodeComplete: "验证验证码并完成注册",
    backToSignIn: "返回登录页面",
    requestNewCode: "验证码已过期？ 重新请求验证码",
    uploadImageTooltip: "上传图片",
    takePhotoTooltip: "拍摄照片",
    readCanvasTooltip: "读取画布/草图",
    voiceInputTooltip: "语音输入",
    insertIntoProject: "插入至项目",
    dragToMoveBubble: "拖拽以移动对话框",
    allProcessAll: "全部 (批量处理)",
    cropPageBorders: "裁剪页面边框",
    cropPageBordersDesc: "检测并移除页面边距",
    splitPanels: "分割分镜",
    splitPanelsDesc: "检测并拆分单个分镜",
    extractTextOcr: "文字识别 (OCR)",
    extractTextOcrDesc: "通过 Gemini Flash 提取文字",
    translateText: "翻译文字",
    processCurrentPage: "处理当前页面",
    batchProcessAll: "批量处理全部页面",
    batchProcessSelected: "批量处理选中的 {count} 页",
    pageTexts: "第 {page} 页文字",
    detectingLayout: "正在检测排版...",
    freeAiDefault: "免费 AI (默认)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Gemini AI 云端引擎",
    geminiDesc: "默认使用 gemini-flash-latest。处理图片或执行翻译需要个人 API 密钥。",
    getGeminiKeyFree: "🔥 免费获取 Gemini API 密钥 (每分钟 15 次免费)",
    geminiApiKeyLabel: "Gemini API 密钥",
    geminiKeyStorageNote: "您的密钥仅存储在浏览器的本地存储中。",
    modelNameLabel: "模型名称",
    puterDesc: "Puter.js 提供 Mistral/Pixtral 模型进行 OCR。若尚未登录 Puter 将弹出登录提示。",
    localLlmDesc: "连接至 Ollama、LM Studio 或任何兼容 OpenAI 的自定义 API。模型需支持 JSON 模式与视觉功能。",
    otherProviderDesc: "请提供 API 基本网址、密钥与模型名称。系统需要兼容 OpenAI 的接口。",
    apiBaseUrl: "API 基本网址",
    customModel: "自定义模型...",
    typeCustomModelName: "输入自定义模型名称...",
    askAiAgent: "询问 AI 助手...",
    slideReorganizeComics: "重组漫画页面",
    slideCreateComic: "创作漫画",
    slideAddTextInsertImages: "添加文字与插入图片",
  },
  fr: {
    madeWith: "Fait avec",
    by: "par Pierre Kollo. Propulsé par une IA avancée.",
    contact: "Contact",
    language: "Langue",
    selectLanguage: "Choisir la langue",
    home: "Accueil",
    read: "Lire",
    create: "Créer",
    convert: "Convertir",
    heroTitle: "Votre suite complète pour e-books et bandes dessinées",
    heroSubtitle: "Lisez, convertissez et créez des bandes dessinées dynamiques, des romans ou des PDF enrichis. Optimisé pour mobile, ordinateur et liseuses E-ink.",
    readCardTitle: "Lecture guidée : Mangas et textes optimisés",
    readCardDesc: "Optimisé pour écrans mobiles et E-ink. Zoom automatique sur les cases de manga ou réagencement des textes pour un grand confort.",
    accessBookshelf: "Accéder à la bibliothèque →",
    createCardTitle: "Créateur de BD en ligne & Éditeur de roman",
    createCardDesc: "Espace de création intuitif. Rédigez des romans, organisez vos scripts ou concevez des planches de BD avec bulles de texte.",
    launchCanvasCreator: "Lancer le créateur →",
    convertCardTitle: "Convertisseur universel d'e-books",
    convertCardDesc: "Convertissez par lots vos fichiers CBZ, CBR, PDF et EPUB. Compressez vos BD et formatez vos e-books pour Kindle.",
    uploadAndConvertNow: "Téléverser et convertir →",
    keyFeaturesTitle: "Fonctionnalités clés & Outils en ligne",
    featAiTranslateTitle: "Outil de traduction IA",
    featAiTranslateDesc: "Traduisez les mangas et webtoons japonais avec une OCR IA avancée. Détection automatique des bulles et nettoyage du texte.",
    featMultiAiTitle: "Choix du fournisseur d'IA",
    featMultiAiDesc: "Choisissez parmi les modèles gratuits, Gemini, OpenAI, Claude ou des LLM locaux pour la traduction et l'OCR.",
    featSplitterTitle: "Découpeur de cases de BD",
    featSplitterDesc: "Découpez intelligemment vos planches de BD pour une lecture guidée optimale sur smartphone et liseuse.",
    featCbzEpubTitle: "Convertisseur CBZ vers EPUB",
    featCbzEpubDesc: "Convertissez instantanément vos archives CBZ/ZIP au format EPUB standard compatible avec toutes les liseuses.",
    featAiAgentTitle: "Créer avec un Agent IA",
    featAiAgentDesc: "Collaborez avec un agent IA pour générer des scénarios, formater des bulles et concevoir le découpage de vos bandes dessinées.",
    featLocalProcTitle: "Traitement local privé",
    featLocalProcDesc: "Configurations auto-hébergées en conteneurs pour garantir la confidentialité totale de vos projets hors ligne.",
    featFormatSupportTitle: "Support de formats universel",
    featFormatSupportDesc: "Ouvrez, lisez et convertissez sans effort les fichiers CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP et HTML.",
    featPenSupportTitle: "Prise en charge du stylet",
    featPenSupportDesc: "Compatible avec Wacom et Apple Pencil (inclinaison et pression). Dessinez comme un artiste professionnel.",
    buyCoffee: "Offrez-moi un café",
    supportEbookcc: "Soutenez ebookcc ! 🎉",
    supportCoffeeDesc: "Merci d'utiliser ebookcc ! Si cet outil vous a aidé, vous pouvez soutenir le créateur en offrant un café. Chaque don aide à maintenir les serveurs en ligne !",
    supportKoFi: "Soutenir sur Ko-fi",
    maybeLater: "Plus tard",
    appSettings: "Paramètres de l'application",
    toggleTheme: "Changer de thème",
    allProcessAll: "Tout (tout traiter)",
    cropPageBorders: "Rogner les bordures",
    cropPageBordersDesc: "Détecter et supprimer les marges",
    splitPanels: "Diviser les cases",
    splitPanelsDesc: "Détecter et séparer les cases",
    extractTextOcr: "Extraire le texte (OCR)",
    extractTextOcrDesc: "Extraire via Gemini Flash",
    translateText: "Traduire le texte",
    processCurrentPage: "Traiter la page actuelle",
    batchProcessAll: "Traiter toutes les pages",
    batchProcessSelected: "Traiter la sélection ({count})",
    pageTexts: "Textes de la page {page}",
    detectingLayout: "Détection de la mise en page...",
    freeAiDefault: "IA Gratuite (Par défaut)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Moteur Cloud Gemini AI",
    geminiDesc: "Nous utilisons gemini-flash-latest par défaut. Clé API requise pour traiter les images et traduire.",
    getGeminiKeyFree: "🔥 Obtenez votre clé API Gemini gratuite (15 requêtes/min)",
    geminiApiKeyLabel: "Clé API Gemini",
    geminiKeyStorageNote: "Votre clé est stockée uniquement dans le stockage local de votre navigateur.",
    modelNameLabel: "Nom du modèle",
    puterDesc: "Puter.js donne accès aux modèles Mistral/Pixtral pour l'OCR. Une connexion sera demandée si besoin.",
    localLlmDesc: "Connectez Ollama, LM Studio ou une API compatible OpenAI. Le modèle doit gérer le mode JSON et la vision.",
    otherProviderDesc: "Renseignez l'URL de base, la clé API et le nom du modèle. Une API compatible OpenAI est requise.",
    apiBaseUrl: "URL de base de l'API",
    customModel: "Modèle personnalisé...",
    typeCustomModelName: "Saisir le nom du modèle...",
    askAiAgent: "Demander à l'agent IA...",
    slideReorganizeComics: "Réorganiser les bandes dessinées",
    slideCreateComic: "Créer une bande dessinée",
    slideAddTextInsertImages: "Ajouter du texte, insérer des images",
  },
  es: {
    madeWith: "Hecho con",
    by: "por Pierre Kollo. Impulsado por IA avanzada.",
    contact: "Contacto",
    language: "Idioma",
    selectLanguage: "Seleccionar idioma",
    home: "Inicio",
    read: "Leer",
    create: "Crear",
    convert: "Convertir",
    heroTitle: "Tu suite integral para libros electrónicos y cómics",
    heroSubtitle: "Lee, convierte y crea cómics dinámicos, novelas de texto o PDF multimedia. Optimizado para móviles, escritorio y dispositivos de tinta electrónica.",
    readCardTitle: "Lectura guiada: Cómics y textos optimizados",
    readCardDesc: "Optimizado para pantallas móviles y tinta electrónica. Enfoque automático en viñetas de manga o reajuste de textos sin zooms molestos.",
    accessBookshelf: "Acceder a la biblioteca →",
    createCardTitle: "Creador de cómics y novelas en línea",
    createCardDesc: "Un espacio intuitivo para escribir novelas, redactar guiones o diseñar viñetas de cómics con bocadillos de diálogo.",
    launchCanvasCreator: "Iniciar el creador →",
    convertCardTitle: "Convertidor universal de e-books",
    convertCardDesc: "Convierte en lote archivos CBZ, CBR, PDF y EPUB. Comprime novelas gráficas y genera EPUBs listos para Kindle.",
    uploadAndConvertNow: "Subir y convertir ahora →",
    keyFeaturesTitle: "Características principales y herramientas",
    featAiTranslateTitle: "Herramienta de traducción IA",
    featAiTranslateDesc: "Traduce mangas y webtoons japoneses con OCR e IA avanzada. Detección automática de globos de texto y limpieza de imágenes.",
    featMultiAiTitle: "Elegir proveedor de IA",
    featMultiAiDesc: "Elige entre modelos gratuitos, Gemini, OpenAI, Claude o LLMs locales para traducción y procesamiento OCR.",
    featSplitterTitle: "Divisor de viñetas de cómic",
    featSplitterDesc: "Recorta y divide viñetas de forma inteligente para ofrecer una experiencia de lectura guiada perfecta en móviles.",
    featCbzEpubTitle: "Convertidor CBZ a EPUB",
    featCbzEpubDesc: "Convierte archivos comprimidos CBZ/ZIP a formato EPUB estándar compatible con cualquier lector digital.",
    featAiAgentTitle: "Crear con Agente de IA",
    featAiAgentDesc: "Colabora con un agente de IA para generar argumentos, dar formato a bocadillos y estructurar tus cómics y e-books.",
    featLocalProcTitle: "Procesamiento local privado",
    featLocalProcDesc: "Opciones de alojamiento propio en contenedores para mantener tus proyectos de cómic completamente privados y fuera de línea.",
    featFormatSupportTitle: "Soporte de formatos universal",
    featFormatSupportDesc: "Abre, visualiza y convierte archivos CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP y HTML con total fluidez.",
    featPenSupportTitle: "Soporte para lápiz óptico",
    featPenSupportDesc: "Compatible con Wacom y Apple Pencil con sensibilidad a inclinación y presión. Dibuja como un profesional.",
    buyCoffee: "Invítame a un café",
    supportEbookcc: "¡Apoya a ebookcc! 🎉",
    supportCoffeeDesc: "¡Gracias por usar ebookcc! Si esta herramienta ha mejorado tu experiencia de lectura y edición, considera apoyar al creador con un café.",
    supportKoFi: "Apoyar en Ko-fi",
    maybeLater: "Quizás luego",
    appSettings: "Configuración de la app",
    toggleTheme: "Cambiar tema",
    allProcessAll: "Todo (procesar todo)",
    cropPageBorders: "Recortar bordes",
    cropPageBordersDesc: "Detectar y eliminar márgenes",
    splitPanels: "Dividir viñetas",
    splitPanelsDesc: "Detectar e individualizar viñetas",
    extractTextOcr: "Extraer texto (OCR)",
    extractTextOcrDesc: "Extraer texto vía Gemini Flash",
    translateText: "Traducir texto",
    processCurrentPage: "Procesar página actual",
    batchProcessAll: "Procesar todas en lote",
    batchProcessSelected: "Procesar seleccionadas ({count})",
    pageTexts: "Textos de la página {page}",
    detectingLayout: "Detectando diseño...",
    freeAiDefault: "IA Gratuita (Por defecto)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Motor en la nube Gemini AI",
    geminiDesc: "Usamos gemini-flash-latest por defecto. Se requiere una clave API personal para procesar imágenes y traducir.",
    getGeminiKeyFree: "🔥 Consigue tu clave API de Gemini gratis (15 peticiones/min gratis)",
    geminiApiKeyLabel: "Clave API de Gemini",
    geminiKeyStorageNote: "Su clave solo se guarda en el almacenamiento local de su navegador.",
    modelNameLabel: "Nombre del modelo",
    puterDesc: "Puter.js ofrece acceso a modelos Mistral/Pixtral para OCR. Se solicitará inicio de sesión si no se ha registrado.",
    localLlmDesc: "Conecte Ollama, LM Studio o cualquier API compatible con OpenAI. El modelo debe soportar modo JSON y visión.",
    otherProviderDesc: "Indique la URL base, clave API y nombre del modelo. Se requiere un endpoint compatible con OpenAI.",
    apiBaseUrl: "URL base de la API",
    customModel: "Modelo personalizado...",
    typeCustomModelName: "Escriba el nombre del modelo...",
    askAiAgent: "Preguntar al agente IA...",
    slideReorganizeComics: "Reorganizar cómics",
    slideCreateComic: "Crear cómic",
    slideAddTextInsertImages: "Añadir texto e insertar imágenes",
  },
  pt: {
    madeWith: "Feito com",
    by: "por Pierre Kollo. Alimentado por IA avançada.",
    contact: "Contato",
    language: "Idioma",
    selectLanguage: "Selecionar idioma",
    home: "Início",
    read: "Ler",
    create: "Criar",
    convert: "Converter",
    heroTitle: "Sua suíte completa para e-books e quadrinhos",
    heroSubtitle: "Leia, converta e crie quadrinhos dinâmicos, romances de texto ou PDFs multimídia. Otimizado para dispositivos móveis, desktop e e-ink.",
    readCardTitle: "Leitura guiada: Quadrinhos e textos otimizados",
    readCardDesc: "Otimizado para telas móveis e E-ink. Foco automático nos quadros do mangá e ajuste de texto sem necessidade de zoom.",
    accessBookshelf: "Acessar estante →",
    createCardTitle: "Criador de quadrinhos e romances online",
    createCardDesc: "Espaço intuitivo de criação. Escreva romances, monte roteiros ou crie tirografias com balões de diálogo.",
    launchCanvasCreator: "Iniciar criador →",
    convertCardTitle: "Conversor universal de e-books",
    convertCardDesc: "Converta em lote arquivos CBZ, CBR, PDF e EPUB. Comprima quadrinhos e crie arquivos EPUB prontos para Kindle.",
    uploadAndConvertNow: "Enviar e converter agora →",
    keyFeaturesTitle: "Recursos principais e ferramentas online",
    featAiTranslateTitle: "Ferramenta de tradução com IA",
    featAiTranslateDesc: "Traduza mangás e webtoons com OCR avançado de IA. Detecção automática de balões e limpeza de texto.",
    featMultiAiTitle: "Escolha o provedor de IA",
    featMultiAiDesc: "Escolha entre modelos gratuitos, Gemini, OpenAI, Claude ou LLMs locais para tradução e OCR flexíveis.",
    featSplitterTitle: "Divisor de quadros de quadrinhos",
    featSplitterDesc: "Recorte e divida páginas de quadrinhos inteligentemente para leitura guiada perfeita em qualquer dispositivo.",
    featCbzEpubTitle: "Conversor CBZ para EPUB",
    featCbzEpubDesc: "Converta arquivos CBZ/ZIP em e-books EPUB padrão imediatamente para máxima compatibilidade.",
    featAiAgentTitle: "Criar com Agente de IA",
    featAiAgentDesc: "Colabore com um agente de IA para criar histórias, formatar balões e planejar quadros de quadrinhos.",
    featLocalProcTitle: "Processamento local privado",
    featLocalProcDesc: "Opções de auto-hospedagem para manter seus projetos de quadrinhos privados e seguros offline.",
    featFormatSupportTitle: "Suporte universal de formatos",
    featFormatSupportDesc: "Abra, veja e converta arquivos CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP e HTML com alta qualidade.",
    featPenSupportTitle: "Suporte para caneta stylus",
    featPenSupportDesc: "Suporte a Wacom e Apple Pencil com inclinação e pressão. Desenhe como um artista profissional.",
    buyCoffee: "Pague-me um café",
    supportEbookcc: "Apoie o ebookcc! 🎉",
    supportCoffeeDesc: "Obrigado por usar o ebookcc! Se esta ferramenta ajudou sua leitura ou criação, considere apoiar o desenvolvedor com um café.",
    supportKoFi: "Apoiar no Ko-fi",
    maybeLater: "Talvez mais tarde",
    appSettings: "Configurações do app",
    toggleTheme: "Alternar tema",
    allProcessAll: "Tudo (processar tudo)",
    cropPageBorders: "Cortar bordas",
    cropPageBordersDesc: "Detectar e remover margens",
    splitPanels: "Dividir painéis",
    splitPanelsDesc: "Detectar e individualizar painéis",
    extractTextOcr: "Extrair texto (OCR)",
    extractTextOcrDesc: "Extrair texto via Gemini Flash",
    translateText: "Traduzir texto",
    processCurrentPage: "Processar página atual",
    batchProcessAll: "Processar todas em lote",
    batchProcessSelected: "Processar selecionadas ({count})",
    pageTexts: "Textos da página {page}",
    detectingLayout: "Detectando layout...",
    freeAiDefault: "IA Gratuita (Padrão)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Motor Cloud Gemini AI",
    geminiDesc: "Usamos gemini-flash-latest por padrão. Você precisa de uma chave API para processar imagens e traduzir.",
    getGeminiKeyFree: "🔥 Obtenha sua chave API Gemini grátis (15 requisições/min grátis)",
    geminiApiKeyLabel: "Chave API Gemini",
    geminiKeyStorageNote: "Sua chave é armazenada apenas no armazenamento local do seu navegador.",
    modelNameLabel: "Nome do modelo",
    puterDesc: "Puter.js fornece acesso aos modelos Mistral/Pixtral para OCR. Um aviso de login aparecerá se necessário.",
    localLlmDesc: "Conecte Ollama, LM Studio ou qualquer API compatível com OpenAI. O modelo deve suportar modo JSON e visão.",
    otherProviderDesc: "Forneça a URL base, chave API e nome do modelo. É esperado um endpoint compatível com OpenAI.",
    apiBaseUrl: "URL base da API",
    customModel: "Modelo personalizado...",
    typeCustomModelName: "Digite o nome do modelo...",
    askAiAgent: "Perguntar ao Agente IA...",
    slideReorganizeComics: "Reorganizar quadrinhos",
    slideCreateComic: "Criar quadrinho",
    slideAddTextInsertImages: "Adicionar texto e inserir imagens",
  },
  ko: {
    madeWith: "제작",
    by: "Pierre Kollo 제작. 첨단 AI 기반.",
    contact: "문의하기",
    language: "언어",
    selectLanguage: "언어 선택",
    home: "홈",
    read: "읽기",
    create: "제작",
    convert: "변환",
    heroTitle: "올인원 전자책 & 코믹 종합 스위트",
    heroSubtitle: "동적 코믹스, 텍스트 소설, 미디어 리치 PDF를 읽고, 변환하고, 작성하세요. 모바일, 데스크톱, 전자종이(E-ink) 기기에 최적화되었습니다.",
    readCardTitle: "가이드 읽기: 만화 & 텍스트 최적화",
    readCardDesc: "모바일 및 E-ink 화면에 최적화. 만화 컷 자동 줌 및 리플로우 텍스트 지원으로 확대/축소 불편을 해소합니다.",
    accessBookshelf: "내 서재 열기 →",
    createCardTitle: "온라인 만화 제작기 & 소설 에디터",
    createCardDesc: "직관적인 리치 텍스트 워크스페이스. 전자책 소설 작성, 콘티 구성, 다중 컷 만화 및 말풍선 디자인 지원.",
    launchCanvasCreator: "캔버스 에디터 실행 →",
    convertCardTitle: "유니버설 전자책 변환기",
    convertCardDesc: "CBZ, CBR, PDF, EPUB 파일 일괄 변환 지원. 만화 압축 및 킨들용 EPUB 서식 변환 가능.",
    uploadAndConvertNow: "지금 업로드 및 변환 →",
    keyFeaturesTitle: "핵심 기능 및 온라인 툴",
    featAiTranslateTitle: "AI 만화 번역 툴",
    featAiTranslateDesc: "첨단 AI OCR을 활용하여 일본어 원작 만화 및 웹툰 번역. 말풍선 자동 감지 및 텍스트 지우기 지원.",
    featMultiAiTitle: "멀티 AI 프로바이더 선택",
    featMultiAiDesc: "무료 모델, Gemini, OpenAI, Claude, 로컬 LLM 중 선택하여 번역 및 OCR을 유연하게 진행하세요.",
    featSplitterTitle: "만화 컷 자르기 스플리터",
    featSplitterDesc: "만화 페이지를 스마트하게 자르고 분할하여 스마트폰에서 완벽한 가이드 뷰어 경험을 제공합니다.",
    featCbzEpubTitle: "CBZ → EPUB 변환기",
    featCbzEpubDesc: "압축 만화 파일(CBZ/ZIP)을 표준 EPUB 전자책 포맷으로 즉시 변환합니다.",
    featAiAgentTitle: "AI 에이전트와 공동 창작",
    featAiAgentDesc: "AI 에이전트와 협업하여 스토리라인 작성, 말풍선 배치, 만화 레이아웃 및 전자책 구성을 진행하세요.",
    featLocalProcTitle: "비공개 로컬 처리",
    featLocalProcDesc: "자체 호스팅 및 컨테이너 환경을 지원하여 만화 프로젝트 데이터를 오프라인에서 안전하게 보호합니다.",
    featFormatSupportTitle: "범용 포맷 지원",
    featFormatSupportDesc: "CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP, HTML 파일을 손쉽게 열고 변환하세요.",
    featPenSupportTitle: "펜/스파일러스 지원",
    featPenSupportDesc: "Wacom 및 Apple Pencil 기울기 및 필압 감지 지원. 전문 작가처럼 자유롭게 그리세요.",
    buyCoffee: "커피 한 잔 후원하기",
    supportEbookcc: "ebookcc 를 후원해 주세요! 🎉",
    supportCoffeeDesc: "ebookcc를 이용해 주셔서 감사합니다! 이 툴이 독서 및 만화 제작에 도움이 되었다면, 개발자에게 따뜻한 커피 한 잔을 선물해 주세요.",
    supportKoFi: "Ko-fi 에서 후원하기",
    maybeLater: "나중에",
    appSettings: "앱 설정",
    toggleTheme: "테마 전환",
    allProcessAll: "전체 (일괄 처리)",
    cropPageBorders: "페이지 테두리 자르기",
    cropPageBordersDesc: "여백 감지 및 제거",
    splitPanels: "컷 분割 (패널 분할)",
    splitPanelsDesc: "개별 컷 감지 및 분할",
    extractTextOcr: "텍스트 추출 (OCR)",
    extractTextOcrDesc: "Gemini Flash로 텍스트 추출",
    translateText: "텍스트 번역",
    processCurrentPage: "현재 페이지 처리",
    batchProcessAll: "모든 페이지 일괄 처리",
    batchProcessSelected: "선택한 {count}개 페이지 일괄 처리",
    pageTexts: "{page} 페이지 텍스트",
    detectingLayout: "레이아웃 감지 중...",
    freeAiDefault: "무료 AI (기본)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Gemini AI 클라우드 엔진",
    geminiDesc: "기본적으로 gemini-flash-latest를 사용합니다. 이미지 처리 및 번역에는 개인 API 키가 필요합니다.",
    getGeminiKeyFree: "🔥 무료 Gemini API 키 받기 (분당 15회 무료)",
    geminiApiKeyLabel: "Gemini API 키",
    geminiKeyStorageNote: "API 키는 브라우저의 로컬 저장소에만 저장됩니다.",
    modelNameLabel: "모델 이름",
    puterDesc: "Puter.js는 OCR을 위해 Mistral/Pixtral 모델 액세스를 제공합니다. 로그인하지 않은 경우 로그인 창이 나타납니다.",
    localLlmDesc: "Ollama, LM Studio 또는 OpenAI 호환 커스텀 엔드포인트에 연결합니다. 모델은 JSON 모드 및 비전 기능을 지원해야 합니다.",
    otherProviderDesc: "기본 URL, API 키 및 모델 이름을 입력하세요. OpenAI 호환 엔드포인트가 필요합니다.",
    apiBaseUrl: "API 기본 URL",
    customModel: "커스텀 모델...",
    typeCustomModelName: "커스텀 모델 이름 입력...",
    askAiAgent: "AI 에이전트에게 문의...",
    slideReorganizeComics: "만화 재구성",
    slideCreateComic: "만화 제작",
    slideAddTextInsertImages: "텍스트 추가 및 이미지 삽입",
  },
  de: {
    madeWith: "Gemacht mit",
    by: "von Pierre Kollo. Angetrieben von fortschrittlicher KI.",
    contact: "Kontakt",
    language: "Sprache",
    selectLanguage: "Sprache auswählen",
    home: "Startseite",
    read: "Lesen",
    create: "Erstellen",
    convert: "Konvertieren",
    heroTitle: "Ihre komplette All-in-One E-Book & Comic Suite",
    heroSubtitle: "Lesen, konvertieren und erstellen Sie dynamische Comics, Textromane oder medienreiche PDFs. Optimiert für Mobilgeräte, Desktop und E-Ink-Lesegeräte.",
    readCardTitle: "Geführtes Lesen: Comics & Text optimiert",
    readCardDesc: "Optimiert für Mobil- und E-Ink-Bildschirme. Automatisch fokussierte Manga-Panels und flüssige Textumformatierung.",
    accessBookshelf: "Zum Bücherregal →",
    createCardTitle: "Online Comic-Maker & Roman-Editor",
    createCardDesc: "Ein intuitiver Rich-Text-Arbeitsbereich. Schreiben Sie E-Books, erstellen Sie Skripte oder gestalten Sie Comics mit Sprechblasen.",
    launchCanvasCreator: "Canvas-Editor starten →",
    convertCardTitle: "Universeller E-Book-Konverter",
    convertCardDesc: "Konvertieren Sie CBZ-, CBR-, PDF- und EPUB-Dateien im Stapelbetrieb. Erstellen Sie Kindle-fertige EPUB-Dateien.",
    uploadAndConvertNow: "Jetzt hochladen & konvertieren →",
    keyFeaturesTitle: "Hauptfunktionen & Online-Tools",
    featAiTranslateTitle: "KI-Übersetzungstool",
    featAiTranslateDesc: "Übersetzen Sie japanische Manga und Webtoons mit fortgeschrittener KI-OCR. Automatische Erkennung von Sprechblasen.",
    featMultiAiTitle: "Multi-KI-Anbieter auswählen",
    featMultiAiDesc: "Wählen Sie zwischen kostenlosen Modellen, Gemini, OpenAI, Claude oder lokalen LLMs für Übersetzung und OCR.",
    featSplitterTitle: "Comic-Panel-Teiler",
    featSplitterDesc: "Schneiden und teilen Sie Comic-Seiten intelligent für ein optimales mobiles Leseerlebnis auf jedem Gerät.",
    featCbzEpubTitle: "CBZ zu EPUB Konverter",
    featCbzEpubDesc: "Wandeln Sie CBZ/ZIP-Comic-Archive sofort in standardmäßige EPUB-E-Books um.",
    featAiAgentTitle: "Mit KI-Agenten erstellen",
    featAiAgentDesc: "Arbeiten Sie mit einem KI-Agenten zusammen, um Handlungen zu generieren, Sprechblasen zu formatieren und E-Books zu strukturieren.",
    featLocalProcTitle: "Private lokale Verarbeitung",
    featLocalProcDesc: "Unterstützt selbstgehostete Container-Umgebungen, um Ihre Comic-Projekte sicher offline zu halten.",
    featFormatSupportTitle: "Universelle Formatunterstützung",
    featFormatSupportDesc: "Öffnen, betrachten und konvertieren Sie CBZ, CBR, EPUB, PDF, DOCX, TXT, WEBP und HTML nahtlos.",
    featPenSupportTitle: "Stiftunterstützung",
    featPenSupportDesc: "Unterstützt Wacom und Apple Pencil mit Neigungs- und Druckempfindlichkeit. Zeichnen Sie wie ein Profi.",
    buyCoffee: "Spendieren Sie einen Kaffee",
    supportEbookcc: "Unterstützen Sie ebookcc! 🎉",
    supportCoffeeDesc: "Vielen Dank, dass Sie ebookcc nutzen! Wenn dieses Tool Ihre Lese- und Editiereffizienz verbessert hat, unterstützen Sie den Entwickler gerne mit einem Kaffee.",
    supportKoFi: "Auf Ko-fi unterstützen",
    maybeLater: "Vielleicht später",
    appSettings: "App-Einstellungen",
    toggleTheme: "Design wechseln",
    allProcessAll: "Alle (alle verarbeiten)",
    cropPageBorders: "Seitenränder beschneiden",
    cropPageBordersDesc: "Ränder erkennen und entfernen",
    splitPanels: "Panels teilen",
    splitPanelsDesc: "Einzelne Panels erkennen",
    extractTextOcr: "Text extrahieren (OCR)",
    extractTextOcrDesc: "Text mit Gemini Flash extrahieren",
    translateText: "Text übersetzen",
    processCurrentPage: "Aktuelle Seite verarbeiten",
    batchProcessAll: "Alle Stapel verarbeiten",
    batchProcessSelected: "Ausgewählte ({count}) verarbeiten",
    pageTexts: "Texte der Seite {page}",
    detectingLayout: "Layout wird erkannt...",
    freeAiDefault: "Kostenlose KI (Standard)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "Gemini AI Cloud-Engine",
    geminiDesc: "Wir verwenden standardmäßig gemini-flash-latest. Für Bildverarbeitung und Übersetzung wird ein API-Schlüssel benötigt.",
    getGeminiKeyFree: "🔥 Kostenlosen Gemini API-Schlüssel holen (15 Anfragen/Min frei)",
    geminiApiKeyLabel: "Gemini API-Schlüssel",
    geminiKeyStorageNote: "Ihr Schlüssel wird nur im lokalen Speicher Ihres Browsers gespeichert.",
    modelNameLabel: "Modellname",
    puterDesc: "Puter.js bietet Zugriff auf Mistral/Pixtral-Modelle für OCR. Bei Bedarf erscheint eine Anmeldeaufforderung.",
    localLlmDesc: "Verbinden Sie Ollama, LM Studio oder eine OpenAI-kompatible Schnittstelle. Modell muss JSON & Vision unterstützen.",
    otherProviderDesc: "Geben Sie Basis-URL, API-Schlüssel und Modellname an. Ein OpenAI-kompatibler Endpunkt wird erwartet.",
    apiBaseUrl: "API-Basis-URL",
    customModel: "Benutzerdefiniertes Modell...",
    typeCustomModelName: "Modellnamen eingeben...",
    askAiAgent: "AI-Agenten fragen...",
    slideReorganizeComics: "Comics reorganisieren",
    slideCreateComic: "Comic erstellen",
    slideAddTextInsertImages: "Text hinzufügen, Bilder einfügen",
  },
  ar: {
    madeWith: "صنع بـ",
    by: "بواسطة Pierre Kollo. مدعوم بالذكاء الاصطناعي المتقدم.",
    contact: "اتصل بنا",
    language: "اللغة",
    selectLanguage: "اختر اللغة",
    home: "الرئيسية",
    read: "قراءة",
    create: "إنشاء",
    convert: "تحويل",
    heroTitle: "جناحك الشامل للكتب الإلكترونية والقصص المصورة",
    heroSubtitle: "اقرأ وحوّل وأنشئ قصصًا مصورة ديناميكية وروايات نصية ووثائق PDF غنية. محسّن للأجهزة المحمولة وأجهزة سطح المكتب وشاشات الحبر الإلكتروني.",
    readCardTitle: "القراءة الموجهة: تحسين القصص المصورة والنصوص",
    readCardDesc: "محسّن للشاشات المحمولة وشاشات الحبر الإلكتروني. التركيز التلقائي على إطارات المانجا وإعادة ترتيب النصوص بسهولة.",
    accessBookshelf: "الذهاب إلى رف الكتب ←",
    createCardTitle: "صانع القصص المصورة ومحرر الروايات عبر الإنترنت",
    createCardDesc: "مساحة عمل احترافية. اكتب الروايات الإلكترونية، ونسّق السيناريوهات، وصمم لوحات القصص المصورة وفقاعات الكلام.",
    launchCanvasCreator: "تشغيل محرر اللوحة ←",
    convertCardTitle: "محول الكتب الإلكترونية الشامل",
    convertCardDesc: "تحويل دفعة من ملفات CBZ و CBR و PDF و EPUB بسهولة. ضغط القصص المصورة وتنسيق EPUB للـ Kindle.",
    uploadAndConvertNow: "رفع وتحويل الآن ←",
    keyFeaturesTitle: "الميزات الرئيسية والأدوات المتاحة",
    featAiTranslateTitle: "أداة الترجمة بالذكاء الاصطناعي",
    featAiTranslateDesc: "ترجمة المانجا والويب تون الياباني باستخدام التقاط النصوص بالذكاء الاصطناعي مع الكشف التلقائي عن الفقاعات.",
    featMultiAiTitle: "اختيار مزود الذكاء الاصطناعي Multi-AI",
    featMultiAiDesc: "اختر من بين النماذج المجانية و Gemini و OpenAI و Claude أو النماذج المحلية للترجمة واستخراج النصوص.",
    featSplitterTitle: "أداة تقطيع إطارات القصص المصورة",
    featSplitterDesc: "قص وتقسيم صفحات القصص المصورة بذكاء لتوفير تجربة قراءة موجهة مثالية على أي جهاز.",
    featCbzEpubTitle: "محول CBZ إلى EPUB",
    featCbzEpubDesc: "تحويل أرشيفات القصص المصورة المضغوطة (CBZ/ZIP) فورًا إلى كتب EPUB قياسية مع توافق كامل.",
    featAiAgentTitle: "الإنشاء مع وكيل الذكاء الاصطناعي",
    featAiAgentDesc: "تعاون مع وكيل ذكاء اصطناعي لإنشاء حبكات القصص وتنسيق الفقاعات وتصميم الهيكل العام للكتب.",
    featLocalProcTitle: "معالجة محلية خاصة",
    featLocalProcDesc: "تكوينات الاستضافة الذاتية متاحة لضمان بقاء مشاريعك خاصة وآمنة دون اتصال بالإنترنت.",
    featFormatSupportTitle: "دعم التنسيقات الشامل",
    featFormatSupportDesc: "فتح وعرض وتحويل ملفات CBZ و CBR و EPUB و PDF و DOCX و TXT و WEBP و HTML بكل سلاسة.",
    featPenSupportTitle: "دعم القلم الضوئي",
    featPenSupportDesc: "يدعم أجهزة Wacom و Apple Pencil مع حساسية الإمالة والضغط. ارسم مثل الفنانين المحترفين.",
    buyCoffee: "اشترِ لي قهوة",
    supportEbookcc: "دعم ebookcc! 🎉",
    supportCoffeeDesc: "شكراً لاستخدامك ebookcc! إذا ساعدتك هذه الأداة في تحسين تجربة القراءة والإنشاء، يرجى دعم المطور بقهوة.",
    supportKoFi: "الدعم عبر Ko-fi",
    maybeLater: "ربما لاحقًا",
    appSettings: "إعدادات التطبيق",
    toggleTheme: "تبديل المظهر",
    allProcessAll: "الكل (معالجة الكل)",
    cropPageBorders: "قص حواف الصفحة",
    cropPageBordersDesc: "كشف وإزالة هوامش الصفحة",
    splitPanels: "تقسيم الإطارات",
    splitPanelsDesc: "كشف وفصل الإطارات",
    extractTextOcr: "استخراج النص (OCR)",
    extractTextOcrDesc: "استخراج النص عبر Gemini Flash",
    translateText: "ترجمة النص",
    processCurrentPage: "معالجة الصفحة الحالية",
    batchProcessAll: "معالجة جميع الصفحات دفعة واحدة",
    batchProcessSelected: "معالجة المحدد ({count})",
    pageTexts: "نصوص الصفحة {page}",
    detectingLayout: "جاري كشف التخطيط...",
    freeAiDefault: "ذكاء اصطناعي مجاني (افتراضي)",
    puterJs: "Puter.js (Mistral/Pixtral)",
    geminiAiCloudEngine: "محرك سحابي Gemini AI",
    geminiDesc: "نستخدم gemini-flash-latest افتراضيًا. تحتاج إلى مفتاح API شخصي لترجمة أو معالجة الصور.",
    getGeminiKeyFree: "🔥 احصل على مفتاح Gemini API المجاني (15 طلبًا في الدقيقة مجانًا)",
    geminiApiKeyLabel: "مفتاح Gemini API",
    geminiKeyStorageNote: "يتم تخزين مفتاحك فقط في التخزين المحلي لمتصفحك.",
    modelNameLabel: "اسم النموذج",
    puterDesc: "يوفر Puter.js إمكانية الوصول إلى نماذج Mistral/Pixtral لـ OCR. سيظهر موجه تسجيل الدخول إذا لم تكن مسجلاً.",
    localLlmDesc: "اتصل بـ Ollama أو LM Studio أو أي نقطة نهاية مخصصة متوافقة مع OpenAI. يجب أن يدعم النموذج وضع JSON والرؤية.",
    otherProviderDesc: "قم بتوفير عنوان URL الأساسي ومفتاح API واسم النموذج. نتوقع نقطة نهاية متوافقة مع OpenAI.",
    apiBaseUrl: "عنوان URL الأساسي لـ API",
    customModel: "نموذج مخصص...",
    typeCustomModelName: "اكتب اسم النموذج المخصص...",
    askAiAgent: "اسأل وكيل الذكاء الاصطناعي...",
    slideReorganizeComics: "إعادة تنظيم القصص المصورة",
    slideCreateComic: "إنشاء قصة مصورة",
    slideAddTextInsertImages: "إضافة نص وإدراج صور",
  },
};

export function detectBrowserLanguage(): LanguageCode {
  if (typeof window === "undefined") return "en";
  const navLangs = navigator.languages || [navigator.language || "en"];
  for (const rawLang of navLangs) {
    if (!rawLang) continue;
    const lang = rawLang.toLowerCase();
    if (lang.startsWith("ja") || lang.startsWith("jp")) return "jp";
    if (
      lang.includes("hant") ||
      lang === "zh-tw" ||
      lang === "zh-hk" ||
      lang === "zh-mo"
    )
      return "zh-Hant";
    if (lang.includes("hans") || lang.startsWith("zh")) return "zh-Hans";
    if (lang.startsWith("fr")) return "fr";
    if (lang.startsWith("es")) return "es";
    if (lang.startsWith("pt")) return "pt";
    if (lang.startsWith("ko")) return "ko";
    if (lang.startsWith("de")) return "de";
    if (lang.startsWith("ar")) return "ar";
    if (lang.startsWith("en")) return "en";
  }
  return "en";
}

export function parseLanguageAndRouteFromPath(pathname: string): {
  lang: LanguageCode | null;
  view: "home" | "read" | "create" | "convert";
} {
  const cleanPath = pathname.trim();
  const segments = cleanPath.split("/").filter(Boolean);

  if (segments.length === 0) {
    return { lang: null, view: "home" };
  }

  const firstSeg = segments[0];
  const matchedLang = LANGUAGES.find(
    (l) =>
      l.code.toLowerCase() === firstSeg.toLowerCase() ||
      l.path.toLowerCase() === `/${firstSeg.toLowerCase()}`
  );

  if (matchedLang) {
    const remainingSeg = segments[1] ? segments[1].toLowerCase() : "";
    let view: "home" | "read" | "create" | "convert" = "home";
    if (remainingSeg === "read") view = "read";
    else if (remainingSeg === "create") view = "create";
    else if (remainingSeg === "convert") view = "convert";
    return { lang: matchedLang.code, view };
  }

  let view: "home" | "read" | "create" | "convert" = "home";
  const seg0 = firstSeg.toLowerCase();
  if (seg0 === "read") view = "read";
  else if (seg0 === "create") view = "create";
  else if (seg0 === "convert") view = "convert";

  return { lang: null, view };
}

export function buildPathWithLanguage(
  lang: LanguageCode,
  view: "home" | "read" | "create" | "convert"
): string {
  const viewPath = view === "home" ? "" : `/${view}`;
  return `/${lang}${viewPath}`;
}

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  currentOption: LanguageOption;
  t: (key: string) => string;
  buildPath: (view: "home" | "read" | "create" | "convert") => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    if (typeof window === "undefined") return "en";
    const { lang } = parseLanguageAndRouteFromPath(window.location.pathname);
    if (lang) return lang;

    const saved = localStorage.getItem("app_lang") as LanguageCode | null;
    if (saved && LANGUAGES.some((l) => l.code === saved)) {
      return saved;
    }

    return detectBrowserLanguage();
  });

  const updateDocumentAttributes = useCallback((langCode: LanguageCode) => {
    if (typeof document === "undefined") return;
    document.documentElement.lang = langCode;
    if (langCode === "ar") {
      document.documentElement.dir = "rtl";
    } else {
      document.documentElement.dir = "ltr";
    }
  }, []);

  useEffect(() => {
    updateDocumentAttributes(language);
  }, [language, updateDocumentAttributes]);

  // Sync state on back/forward browser navigation
  useEffect(() => {
    const handlePopState = () => {
      const { lang } = parseLanguageAndRouteFromPath(window.location.pathname);
      if (lang) {
        setLanguageState(lang);
      }
    };
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  const setLanguage = useCallback(
    (code: LanguageCode) => {
      setLanguageState(code);
      localStorage.setItem("app_lang", code);
      updateDocumentAttributes(code);

      // Update URL pathname with current route and new language prefix without full reload
      if (typeof window !== "undefined") {
        const { view } = parseLanguageAndRouteFromPath(window.location.pathname);
        const newPath = buildPathWithLanguage(code, view);
        window.history.pushState(null, "", newPath);
      }
    },
    [updateDocumentAttributes]
  );

  const currentOption =
    LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  const t = useCallback(
    (key: string): string => {
      const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
      return dict[key] || TRANSLATIONS.en[key] || key;
    },
    [language]
  );

  const buildPath = useCallback(
    (view: "home" | "read" | "create" | "convert") => {
      return buildPathWithLanguage(language, view);
    },
    [language]
  );

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentOption,
        t,
        buildPath,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
